### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
import numpy as np
N = 10
desc_array = np.arange(N-1, -1, -1)
print(desc_array)

[9 8 7 6 5 4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
my_diag = np.diag(desc_array)
print(my_diag)
trace = my_diag.trace()
print('След =', trace)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
След = 45


### Задание 3
Решите систему уравнений:
    4x + 2y + z = 4;
    x + 3y = 12;
    5y + 4z = -3;

In [35]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x, y, z = np.linalg.solve(a, b)
# or
x1, y1, z1 = np.dot(np.linalg.inv(a), b)

print('x =', x, '\ny =', y, '\nz =', z)

x = 0.4666666666666668 
y = 3.844444444444444 
z = -5.555555555555555
